### ISSUE TITLE
optimizedhtml-start-template

### ISSUE THREAD

**Issue by RomanHristofor** [agragregra/optimizedhtml-start-template#10]
привет, Алексей. спасибо за шаблон!) 
решил попробовать его

использую его впервые, посмотрел видео по нему, тем не менее есть вопрос:

при загрузке страницы видно как элементы собираются, а этого быть не должно.

в чем может быть дело?

**Comment by kolyaraketa** [comment]
Такое может быть если ты используешь transition all, либо если не все стили первого экрана вынесены в хедер.сасс, либо на мобильном устройстве не вынесены брейкпоинты со стилями хедера в хедер.сасс

Сначала нужно сделать build, потом уже смотреть результат на выходе. Может быть ты смотришь во время разработки.

**Comment by RomanHristofor** [comment]
- transition all - нет( только для кнопки burger-menu)
- все стили для первого экрана в header.sass
- для mobile device использовал миксин для @media queries и писал все в файле header.sass, то что для первого экрана

**Comment by kolyaraketa** [comment]
Если ты действительно все это сделал правильно, то у тебя хедер должен загружаться практически мгновенно, если конечно там не тяжелая картинка. У меня проблем с этим нет.

**Comment by RomanHristofor** [comment]
нет, картинок нет тяжелых. 
img хорошо сжались - в этом вопросе все работает отлично. экзиф вырезается)

**Comment by RomanHristofor** [comment]
особенно хорошо заметна проблема с выпадающим меню (First screen), при загрузке сайта на мобильном устройстве.
могу скинуть на email ссылку на сайт

**Comment by kolyaraketa** [comment]
Проблему с выпадающим меню я решал с помощью visible: hidden, еще с transition поиграться нужно. Если необходимо - можно с помощью js потом добавлять транзишн, но что бы при загрузке ничего не мелькало.

Могу скинуть свой пример реализации такого велосипеда, копаться в твоем коде нет времени, увы

**Comment by wdmcourses** [comment]
RomanHristofor, напишите тут.

**Comment by RomanHristofor** [comment]
да, хорошо скинь пример своего велосипеда)
про копаться в моем коде - я и не просил, хотел просто чтоб визуально ты глянул на внешний вид и возможно определить в сторону js и/или css смотреть.

**Comment by kolyaraketa** [comment]
вот мой один из последних - http://pb.lexstatus.com.ua/, конечно немного мелькает сама картинка пока не прогрузилась, но это делается все ооочень быстро и практически незаметно. Можно конечно заморочиться и что-то еще придумать, но я не стал. Меню не мелькает, можешь посмотреть как это сделано.

**Comment by RomanHristofor** [comment]
спасибо, посмотрел) а то что все ездит - это так задумано?)

**Comment by kolyaraketa** [comment]
ну как бы да, прихоть дизайнера )

**Comment by tov-jukov** [comment]
Немного в глазах рябит от такого эффекта "езды".
