### ISSUE TITLE
Потерялась папка css ?

### ISSUE THREAD

**Issue by ve1ikiy-zz** [agragregra/optimizedhtml-start-template#13]
В app/ нет папки css, и нет начального файла стилей который должен подключаться. 
Так и должно быть, или файл где-то потерялся?

**Comment by kolyaraketa** [comment]
Все начальные стили лежат в SASS файле, Gulp сам все создаст.

**Comment by Vjacheslav143** [comment]
При запуске вылетает ошибка.
