### ISSUE TITLE
Gulp-watch\bootstrap-grid

### ISSUE THREAD

**Issue by Zik42** [agragregra/optimizedhtml-start-template#14]
Проблема! Когда запускаешь gulp, media бустрапа срабатывают не там где нужно (1092px , a не 992px) и другое... Помогите прошу, не могу найти почему так. Когда открываю отдельно index.html медиа запросы применяются верно.

**Comment by kolyaraketa** [comment]
Измени в файле с медиа-выражениями необходимое значение или добавь свое.

**Comment by Zik42** [comment]
Прошу прощения, если вы о значениях в самой бустрап сетки медиа запросов, то они по умолчанию стоят. Проблема с gulp, с ним срабатывают запросы неправильно, а когда без него, открываю, чисто index.html , .сontainter правильно изменяет свой размер....
