### ISSUE TITLE
@@include('header.min.css')

### ISSUE THREAD

**Issue by KhalitovAdel** [agragregra/optimizedhtml-start-template#17]
Во время разработки не вставляются стили
@@include('header.min.css') так и не раскрывается

В чем проблема:?

**Comment by kolyaraketa** [comment]
Ошибок в консоли нет никаких? Проверьте, что бы были установлены все плагины, в частности `gulp-file-include` и `gulp-remove-html`

**Comment by KhalitovAdel** [comment]
header.min.css из header.scss не компилируется, элементарно он пустой. Может в этом причина?

**Comment by KhalitovAdel** [comment]
`C:\projects\jur2>npm i gulp-file-include
optimizedhtml@2.0.0 C:\projects\jur2
`-- gulp-file-include@1.0.0
  `-- flatnest@1.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optimizedhtml@2.0.0 No repository field.

C:\projects\jur2>npm i gulp-remove-html
optimizedhtml@2.0.0 C:\projects\jur2
`-- gulp-remove-html@1.3.0
  +-- assert@1.4.1
  | `-- util@0.10.3
  |   `-- inherits@2.0.1
  `-- event-stream@3.3.4
    +-- duplexer@0.1.1
    +-- from@0.1.3
    +-- map-stream@0.1.0
    +-- pause-stream@0.0.11
    +-- split@0.3.3
    +-- stream-combiner@0.0.4
    `-- through@2.3.8

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optimizedhtml@2.0.0 No repository field.`

**Comment by KhalitovAdel** [comment]
Проблема в header.min.css из header.scss не компилируется

**Comment by KhalitovAdel** [comment]
`var gulp           = require('gulp'),
		gutil          = require('gulp-util' ),
		sass           = require('gulp-sass'),
		browserSync    = require('browser-sync'),
		concat         = require('gulp-concat'),
		uglify         = require('gulp-uglify'),
		cleanCSS       = require('gulp-clean-css'),
		rename         = require('gulp-rename'),
		del            = require('del'),
		imagemin       = require('gulp-imagemin'),
		cache          = require('gulp-cache'),
		autoprefixer   = require('gulp-autoprefixer'),
		bourbon        = require('node-bourbon'),
		ftp            = require('vinyl-ftp'),
		notify         = require("gulp-notify");

// Скрипты проекта
gulp.task('scripts', function() {
	return gulp.src([
		'app/libs/jquery/dist/jquery.min.js',
		'app/js/common.js', // Всегда в конце
		])
	.pipe(concat('scripts.min.js'))
	.pipe(uglify())
	.pipe(gulp.dest('app/js'))
	.pipe(browserSync.reload({stream: true}));
});

gulp.task('browser-sync', function() {
	browserSync({
		server: {
			baseDir: 'app'
		},
		notify: false
	});
});

gulp.task('sass', function() {
	return gulp.src('app/sass/**/*.scss')
	.pipe(sass({
		includePaths: bourbon.includePaths
	}).on("error", notify.onError()))
	.pipe(rename({suffix: '.min', prefix : ''}))
	.pipe(autoprefixer(['last 15 versions']))
	.pipe(cleanCSS())
	.pipe(gulp.dest('app/css'))
	.pipe(browserSync.reload({stream: true}));
});

gulp.task('watch', ['sass', 'scripts', 'browser-sync'], function() {
	gulp.watch('app/sass/**/*.scss', ['sass']);
	gulp.watch(['libs/**/*.js', 'app/js/common.js'], ['scripts']);
	gulp.watch('app/*.html', browserSync.reload);
});

gulp.task('imagemin', function() {
	return gulp.src('app/img/**/*')
	.pipe(cache(imagemin()))
	.pipe(gulp.dest('dist/img')); 
});

gulp.task('build', ['removedist', 'imagemin', 'sass', 'scripts'], function() {

	var buildFiles = gulp.src([
		'app/*.html',
		'app/.htaccess'
		]).pipe(gulp.dest('dist'));

	var buildCss = gulp.src([
		'app/css/main.min.css',
		]).pipe(gulp.dest('dist/css'));

	var buildJs = gulp.src([
		'app/js/scripts.min.js'
		]).pipe(gulp.dest('dist/js'));

	var buildFonts = gulp.src([
		'app/fonts/**/*']
		).pipe(gulp.dest('dist/fonts'));

});

gulp.task('deploy', function() {

	var conn = ftp.create({
		host:      'hostname.com',
		user:      'username',
		password:  'userpassword',
		parallel:  10,
		log: gutil.log
	});

	var globs = [
	'dist/**',
	'dist/.htaccess',
	];
	return gulp.src(globs, {buffer: false})
	.pipe(conn.dest('/path/to/folder/on/server'));

});

gulp.task('removedist', function() { return del.sync('dist'); });
gulp.task('clearcache', function () { return cache.clearAll(); });

gulp.task('default', ['watch']);
`


Изменения только c sass на scss, причем только header.scss не компилируется, остальные работают исправно!

**Comment by KhalitovAdel** [comment]
Все решилось, gulpfile битый
