### ISSUE TITLE
Readme не соответствует index.html

### ISSUE THREAD

**Issue by r3code** [agragregra/optimizedhtml-start-template#18]
Посмотрел Readme начал смотреть index.html, но описанных комментариев в нем нет.
Посмотрел историю - вижу были, но вы их стерли или заменили на другие.
Обновите Readme, иначе непонятно к чему инструкция.

**Comment by LipinArts** [comment]
Очень актуальный вопрос!!!

**Comment by r3code** [comment]
Так что Readme викинуть и работать по сорсам? НЕ понял, почему закрыли.
