### ISSUE TITLE
Не работает import font

### ISSUE THREAD

**Issue by m1kash** [agragregra/optimizedhtml-start-template#20]
После обновления не работает...
Error: File to import not found or unreadable: fonts.
       Parent style sheet: C:/DB/gderm/app/sass/main.sass
        on line 1 of app/sass/main.sass
>> @import "fonts";
   ^

**Comment by makc9I** [comment]
Бурбон отключили, а шрифты раньше подключались миксином бурбона. Подключайте шрифты обычным способом

**Comment by wdmcourses** [comment]
Здесь есть миксин для работы со шрифтами. Всё работает.
