### ISSUE TITLE
Конфликт magnific-popup и overflow-x: hidden

### ISSUE THREAD

**Issue by JaxonVex** [agragregra/optimizedhtml-start-template#22]
При использовании magnific-popup экран сдвигается вверх. Это происходит из-за overflow-x: hidden.

**Comment by kolyaraketa** [comment]
Не используй magnific-popup

**Comment by isddxy** [comment]
Здравствуй. Почему?

**Comment by JaxonVex** [comment]
Автор сам им пользуется

**Comment by a-zhary** [comment]
Есть опция fixedContentPos
попробуй задать false
$('.popup').magnificPopup({
		type:'image',
		fixedContentPos: false,
	});

**Comment by JaxonVex** [comment]
Спасибо
