### ISSUE TITLE
media queries не работают

### ISSUE THREAD

**Issue by hex0gen** [agragregra/optimizedhtml-start-template#25]
Православненько правлю _media.sass, но результат компиляции в main.min.css огорчает. Не появляются там эти конструкции. Идут друг за другом без размещения в блоках @media просто в слошную в том же порядке что и в sass файле. В чем может быть причина?

P.S. Спасибо за хороший стартовый шаблон

**Comment by hex0gen** [comment]
Чтож похоже мне нужно было прежде разобраться с синтаксисом SASS. Еще раз спасибо за билд

**Comment by kirillz** [comment]
И все таки не работают, код в _media.sass обрабатывается но не реагирует на смену разрешений. Подскажите что может быть не так? Уже голову сломал, новый проект optimized_html скачивал, менял браузеры. Результат тот же.

```/* Extra Small Devices, Phones */
@media only screen and (max-width:480px)
body
  background-color: red
```

Все стало красным но не реагирует на смену разрешений в devtools. Помогите.
Проект готов а заадаптивить не могу

**Comment by skorolevskiy** [comment]
@kirillz Так ты не правильно написал. Нужно сделать на один уровень выше 
```
@media only screen and (max-width:480px) 
    body
        background-color: red
```
Вот так

**Comment by kirillz** [comment]
Ой спасибо тебе Добрый человек! Все заработало!!!! Ура!
