### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by B0dyn** [agragregra/optimizedhtml-start-template#26]
Алексей, спасибо за Ваш труд. 
Вопрос по optimizedhtml-start-template : при изменении main.sass gulp отрабатывает отлично, а вот при изменении  _font.sass, _media.sass и других фрагментов, gulp в ком.строку выдает

```
[22:19:15] gulp-notify: [Error running Gulp] app\sass\main.sass
Error: File to import not found or unreadable: vars.
       Parent style sheet: D:/00_MyWEB/_My_WORK/Orange/sun-orange/app/sass/main.sass
        on line 3 of app/sass/main.sass
>> @import "vars";
   ^
[22:19:16] Finished 'sass' after 51 ms
```

и хотя после ошибки он пишет finished, но по факту не "лайфрелоадит" изменения до следующего перезапуска...
Что сделать, что бы поправить ситуацию?﻿

**Comment by B0dyn** [comment]
Прошу прощения. Проблема оказалась в настройках сублайма: была включена опция сохранения документа при потере фокуса. Если сохранять документ принудительно вышеописанных ошибок нет. Возможно ли (как) в gulpfile добавить задержку перед тем, как выполнится команда "browser-sync"?

**Comment by HamoNazaryan** [comment]
а как отключить эту опцию , у меня такая же проблема ((
