### ISSUE TITLE
Не пора ли перейти на bootstrap 4?

### ISSUE THREAD

**Issue by makc9I** [agragregra/optimizedhtml-start-template#28]
FlexBox поддержка уже очень хорошая. Как минимум будем иметь вертикальное выравнивание без хаков + более современная верстка на флексах, вместо float блоков

**Comment by silencerspirit** [comment]
@makc9I Последний проект был на bootstrap4, впечатление просто FIRE! Очень понравился.

**Comment by kolyaraketa** [comment]
Не пора ли верстать без bootstrap?

**Comment by silencerspirit** [comment]
@kolyaraketa Это странный вопрос...  У бустрапа больше плюсов чем минусов, а с нынешней версией на flex-box они вообще сводятся к нулю.

**Comment by wdmcourses** [comment]
@kolyaraketa я тоже был противником фреймворков. Когда только начинал. Преимущественно по той причине, что они были мне не до конца понятны и вызывали естественный страх перед изучением чего-то не до конца понятного в практическом плане.

**Comment by kolyaraketa** [comment]
@agragregra Отличный ответ, но вот только я уж далеко не начинающий) И если верстка - это не прототипирование интерфейса - бутстрап тут незачем, использую самописную сетку на флексах. Я прекрасно понимаю как работает каждая строчка в бутстрапе, именно по этой причине я от него отказался давно (с нового 2017 года, когда поддержка флексов стала нормальной), потому что нет желания больше плясать вокруг него, пытаясь вписать в него макет.

А так да, бустрап - это инструмент, и использовать его нужно по назначению, и вот там он действительно хорош.
