### ISSUE TITLE
Лишние стили в  Bootstrap Grid

### ISSUE THREAD

**Issue by Ferym26** [agragregra/optimizedhtml-start-template#3]
Написано  а по факту куча общих стилей.
Можно ли оставить только то, что относится конкретно к сетке?

**Comment by Ferym26** [comment]
Алексей, а в чем собственно проблема?

**Comment by wdmcourses** [comment]
Проблема не имеет ни чего общего с реальностью. Здесь представлены общие стили бутстрап + стили сетки, сгенерированные в кастомайзере, в том числе, нормалайз.

**Comment by Ferym26** [comment]
Тогда видимо будет уместным указать это в комменте
