### ISSUE TITLE
Gulp работает  но что то не так с Браузерсинх

### ISSUE THREAD

**Issue by HamoNazaryan** [agragregra/optimizedhtml-start-template#34]
Гулп нормально работает но  не показывает сервера  и за сколько время синхронизировал, проблема не критична , но хотелось бы понять в чем дело , вот скриншот. Кто нибудь сталкивался с такой проблемой?

https://prnt.sc/hnxuhs   --- скриншот

**Comment by vadim1884321** [comment]
Это не проблема галпа, просто в последних версиях Windows 10, изменили цветовую схему у powershell'a. Синий цвет фона powershell и такой же цвет у дополнительных параметров node.js. они сливаются.
Решение:  Или меняем основной терминал т.е. powershell на командную строку в параметрах системы. Или оставляем powershell, но проделываем определенные действия:

1. Запустить powershell от имени администратора.
2. Даем разрешение на запуск скриптов и подтверждаем командой: `Set-ExecutionPolicy RemoteSigned`.
3. Создаем свой профиль для powershell, командой: `New-Item -type file $PROFILE`
4. В документах, заходим в папку PowerShell и открываем для редактирования файл **Microsoft.PowerShell_profile.ps1**. в контекстном меню выбираем "изменить".
5. Вставляем и сохраняем следующий код:
```
(Get-Host).UI.RawUI.ForegroundColor="Gray";
(Get-Host).UI.RawUI.backgroundColor="Black";
(Get-Host).UI.RawUI.CursorSize=10;
(Get-Host).UI.RawUI.WindowTitle="WorldCount Console";
cls
```
Перезапускаем powershell. Вот таким образом можно поменять визуальную конфигурацию powershell'a.
P.S. С цветами можно поиграться, доступные цвета: Black, DarkBlue, DarkGreen, DarkCyan, DarkRed, DarkMagenta, DarkYellow, Gray, DarkGray, Blue, Green, Cyan, Red, Magenta, Yellow, White.

**Comment by HamoNazaryan** [comment]
Спасибо за помощь, делаю как вы сказали , но не могу создать профил, выдает ошибку, вот скриншот

https://prnt.sc/ho7jgr

**Comment by vadim1884321** [comment]
Попробуйте создать в _моих документах_, папку с именем **WindowsPowerShell** и снова повторить команду `New-Item -type file $PROFILE` в powershell от имени администратора.

**Comment by HamoNazaryan** [comment]
Спасибо получилось !!!
