### ISSUE TITLE
Error Gulp Notify

### ISSUE THREAD

**Issue by joy777** [agragregra/optimizedhtml-start-template#38]
Вот такую ошибку стал выдавать.
На всех проектах стало так, при сохранении кода из "fonts", "vars", "libs".
И при открытии чистого шаблона тоже самое.
С чем это может быть связано? Было ли у кого-нибудь что-то подобное?

![default](https://user-images.githubusercontent.com/20818659/35686985-a14b337a-077e-11e8-8961-47b6c46e5526.png)

**Comment by wdmcourses** [comment]
Кириллица в пути. Ваш юзер должен быть латинописным.

**Comment by AntonLitvin** [comment]
У меня такая же ошибка переодически на файле media.scss, приходится дополнительно сохранять еще и главный файл стилей, чтобы все отработало.

**Comment by joy777** [comment]
Я изменил все на латинницу, и все-равно та же ошибка.

**Comment by joy777** [comment]
Все пути изменил на латиницу, все-равно выдает тоже самое. Как тогда отследить в каком месте кириллица и изменить ее?

![default](https://user-images.githubusercontent.com/20818659/35778879-977d61ca-09d5-11e8-9414-5eff03b83f37.png)

**Comment by npofopr** [comment]
Вы лучше ссылку на проект выложите, гадать на скриншотах тяжело.

**Comment by joy777** [comment]
D:\!!!my-work\local-host\StroyKrsk>gulp

**Comment by joy777** [comment]
Я пробовал с разных путей зайти, с диска C и D, все-равно не с того не с сего такая ерунда. На кануне слетали шрифты в компе, я восстановил. Возможно после этого как-то стало. Но путь без кириллицы - определенно.

**Comment by npofopr** [comment]
Я имею ввиду, выложите на тот же гитхаб, чтобы можно было скачать и попробовать запустить в другом месте. 
Лишнее/ личное, разумеется можете убрать.
