### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by slavame** [agragregra/optimizedhtml-start-template#39]
Добрый день!

Скачал как есть и запустил

http://take.ms/6IxCD

Как поправить?

**Comment by skorolevskiy** [comment]
У тебя ошибка в main.sass

**Comment by slavame** [comment]
Файлы не правились, как скачал с отсюда.
@import "fonts"
@import "libs"
@import "vars"

*
	-webkit-box-sizing: border-box
	-moz-box-sizing: border-box
	box-sizing: border-box
	&:before, &:after
		-webkit-box-sizing: border-box
		-moz-box-sizing: border-box
		box-sizing: border-box

*::-webkit-input-placeholder
	color: #666
	opacity: 1

*:-moz-placeholder
	color: #666
	opacity: 1

*::-moz-placeholder
	color: #666
	opacity: 1

*:-ms-input-placeholder
	color: #666
	opacity: 1

body input:focus:required:invalid,
body textarea:focus:required:invalid
	color: #666
body input:required:valid,
body textarea:required:valid
	color: #666

html, body
	height: 100%

body
	font-size: 16px
	min-width: 320px
	position: relative
	line-height: 1.65
	font-family: $default-font
	overflow-x: hidden

.img-responsive
	display: block
	max-width: 100%
	height: auto

.text-center
	text-align: center

::selection
	background-color: $accent
	color: #fff

@import "media" // Всегда в конце

**Comment by slavame** [comment]
Разобрался с ошибкой. 
Дело в том, что у меня стоял какой-то плагин к Sublime 3, который перед компиляцией форматировал файл и далее понятно ошибки формата sass
