### ISSUE TITLE
Ошибка в app/sass/_libs.sass при запуске gulp

### ISSUE THREAD

**Issue by kirillz** [agragregra/optimizedhtml-start-template#42]
![screenshot_20180427_003659](https://user-images.githubusercontent.com/1161809/39333325-249fcc9c-49b3-11e8-9d6a-c2cc3579f6f8.png)
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

**Comment by wdmcourses** [comment]
Импортируйте с расширением .css

**Comment by kirillz** [comment]
Сменил расширение на .css в _libs.sass ошибки нет.

 Благодарю. :grinning:
