### ISSUE TITLE
предупреждение при импорте .css файлов в sass

### ISSUE THREAD

**Issue by nunjuck** [agragregra/optimizedhtml-start-template#43]
Сейчас вылезает предупреждение при импорте .css файлов в sass. Разработчики обещают устранить данную ошибку в версии 3.6 libsass

https://github.com/sass/libsass/releases

Подскажите как-то можно обойти данное предупреждение? из-за него при обновление sass файлов не срабатывает browser-sync

**Comment by wdmcourses** [comment]
Нужно просто добавить расширение .css

**Comment by wdmcourses** [comment]
И скачайте новую версию стартера, только что обновил.

**Comment by nunjuck** [comment]
Спасибо большое! Я первым делом сначала так и сделал, но что-то не сработало, видать ошибку допустил при добавление расширения, а сейчас все ок!
