### ISSUE TITLE
Актуально или нет?

### ISSUE THREAD

**Issue by Chikistq** [agragregra/optimizedhtml-start-template#46]
Актуально или нет использовать "приемы" из урока по оптимизации загрузки, например такие:
1. размещение сетки бутстрап сразу в html > style  
2. размещение таким же образом ccs для Header, т..к отдельным файлом и далее компилировать....
3. подключение ccs скриптами  
и тп.

Почему спрашиваю - урок достаточно старый, 2016 вроде. А сейчас смотрю у тебя более актуальные уроки, например про CSS Grid или сборки галпа ..html4 -  где ты используешь сасс с компиляцией всех файлов в один ..min.css. И подключаешь его link'ом в хеде. Тоже самое и с ...min.js. 

Я так понимаю последний вариант сейчас более правильный и быстрый?

**Comment by wdmcourses** [comment]
Как вы могли заметить, здесь много стартеров. Ничего страшного в использовании того или другого нет. Они являются дополнительными материалами к различным урокам на YouTube и поддерживаются в актуальном состоянии для этих курсов. Это сделано для того, чтобы новички не запутались в процессе обучения и имели возможность потренероваться на тех инструментах, которые я показывал в видео и именно так, как было задумано в уроках.
Самый универсальный стартер на данный момент, который использую я (на данный момент) и который обновляется более глобально - https://github.com/agragregra/OptimizedHTML-4
